### PR TITLE
Initial version of IR2 package versions

### PR DESCRIPTION
**Pull request by heather999**
At Jim's request, I created an initial guess for IR2_TS8_versions.txt using BNL_TS8_1_versions.txt and BNL_TS5_versions.txt as a starting point.
Some items to note:

-  harnessed-jobs = 0.4.38 as that was the higher version as specified in BNL_TS5_versions
- org-lsst-ccs-subsystem-metrology-* appear in BNL_TS5_versions, so they are included here
- [eups_packages] and [packages] sections are in BNL_TS5_versions, is that what we want here?

### CODE REVIEW

**Comment by jchiang87** [comment]
I've folded in the JH-related package versions from BNL_TS8_servers_versions.txt (which strangely predates BNL_TS8_1_versions.txt though it has later versions) and resolved conflicts in the JH-related package versions among the three BNL files.   Someone with CCS expertise will need to make sure the `[ccs]` versions are correct.

**Comment by heather999** [comment]
Do we need to poke Max and/or Tony to get the CCS versions checked?

**Comment by mxturri** [comment]
I am sure I am NOT the right person to answer this question, since I don't fully understand the scope of these version files.
It seems to me that the BNL and the IR2 setup are so different that they require separate version files for JH and CCS related versions.
Right now we have CCS version files in https://github.com/lsst-camera-dh/dev-package-lists where we have one for each computer/HCU.

Why do you need to have CCS versions in there?
What would happen if you removed them?

**Comment by heather999** [comment]
We were just in a meeting with Tony, where he reminded us that the CCS installation would be handled separately.  Jim is planning to update this package list accordingly.  So indeed, you're right Max.  We'll get the harnessed_jobs and associated bits installed and go from there.

**Comment by jchiang87** [comment]
The CCS sections and separate version files have been removed from this branch.  Having them live in dev-package-lists sort of breaks our model for CCB controlled releases, but at least the Job Harness-related code can be handled with existing procedures.  As far as I can tell, the current version of IR2_JH_versions.txt is complete and up-to-date.

@heather999 I talked briefly with Tony at lunch, and he indicated that we could have dev and prod installations of the JH-related code on IR2 just as we do for SLAC_Offline.  Can you please install the packages currently in IR2_JH_versions.txt in a dev area on the diagnostic cluster machine?  Then Max and I will be able to start trying out BNL scripts next week.

**Comment by jchiang87** [comment]
@heather999 nevermind, I'll install what we need to proceed.

**Comment by heather999** [comment]
sorry - I didn't see your updates immediately... it does help to explicitly mention me so I see the email.

I'll go ahead and install .. and you can choose whether to use it or not @jchiang87

**Comment by jchiang87** [comment]
I did explicitly mention you in that note @heather999 !

**Comment by heather999** [comment]
I added datacat and this now represents what is currently installed as dev on lsst-dc10

**Pull request merged**
